services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:80"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
    command: fastapi dev --host 0.0.0.0 --port 80 main.py
